
// let translationKeys = {
//     "00.translator.warning": "--------------------------------------------------------------------------------------------------------",
//     "01.translator.warning": "                                                                                                        ",
//     "02.translator.warning": "DO NOT EDIT THIS FILE MANUALLY. This was generated by: kubejs/server_scripts/datagen/generateTooltips.js",
//     "03.translator.warning": "                                                                                                        ",
//     "04.translator.warning": "--------------------------------------------------------------------------------------------------------",
//     "05.translator.warning": "                                                                                                        "
// };
// const getTooltipPath = (itemId) => {
//     let splitItem = itemId.split(":");
//     return `${splitItem[0]}.${splitItem[1]}`;
// }

// const generateBulkStandardsTooltips = (items, tooltips) => {
//     items.forEach((item) => {
//         let path = getTooltipPath(item);
//         tooltips.forEach((alwaysTip, alwaysIndex) => {
//             translationKeys[`tooltip.always.${path}.${alwaysIndex}`] = `<ltcolor>c=AAAAAA;${alwaysTip}</ltcolor>`;
//         })
//     })
// }
// const generateStandardTooltips = (tooltipArray) => {
//     tooltipArray.forEach((entry) => {
//         let path = getTooltipPath(entry.item);
//         entry.tooltips.forEach((alwaysTip, alwaysIndex) => {
//             translationKeys[`tooltip.always.${path}.${alwaysIndex}`] = alwaysTip;
//         })
//     })
// }
// const generateColorWrappedTooltip = (tooltipArray, hexColor, additionalAlwaysTooltip) => {
//     tooltipArray.forEach((entry) => {
//         let path = getTooltipPath(entry.item);
//         entry.tooltips.forEach((alwaysTip, alwaysIndex) => {
//             translationKeys[`tooltip.always.${path}.${alwaysIndex}`] = `<ltcolor>c=${hexColor};${alwaysTip}</ltcolor>`;
//         })
//         if (additionalAlwaysTooltip) translationKeys[`tooltip.always.${path}.${entry.tooltips.length}`] = additionalAlwaysTooltip;
//     })
// }

// const cardTooltips = [
// ];
// const createLockCardTooltips = (type) => {
//     cardTooltips.push({ item: `scp:${type}_hallway_expansion_card`, tooltips: [`Use on a ${global.formatName(type)} Hallway Lock to unlock it and add a hallway.`, `Containment Units: 2`, `Hallways: 1`] });
//     [
//         { hallType: "left", containmentUnits: 2, hallways: 1, description: "left turn" }, 
//         { hallType: "right", containmentUnits: 2, hallways: 1, description: "right turn" }, 
//         { hallType: "t_intersection", containmentUnits: 1, hallways: 2, description: "T intersection" }, 
//         { hallType: "cross_intersection", containmentUnits: 0, hallways: 3, description: "cross intersection" }, 
//         { hallType: "dead_end", containmentUnits: 3, hallways: 0, description: "dead end" }
//     ].forEach((direction) => {
//          cardTooltips.push({ item: `scp:${type}_hallway_${direction.hallType}_expansion_card`, tooltips: [`Use on a ${global.formatName(type)} Hallway Lock to unlock it and add a ${direction.description}.`, `Containment Units: ${direction.containmentUnits}`, `Hallways: ${direction.hallways}`] })
//     })
//     cardTooltips.push({ item: `scp:${type}_containment_expansion_card`, tooltips: [`Use on a ${global.formatName(type)} Containment Unit lock to unlock it and add a unit.`] })
// };

// [
//     "verdant",
//     "amber",
//     "maroon",
//     "indigo",
// ].forEach((color) => {
//     createLockCardTooltips(color);
// });

// generateStandardTooltips(cardTooltips)

// JsonIO.write(`kubejs/assets/scp_tooltips/lang/en_us.json`, translationKeys);

